---
# This playbook is responsible for installing Hashcat
# and all the related hashcat generators such
# as princeprocessor and hashcat_utils

- name: Install Hashcat
  include_tasks: hashcat.yml

- name: Install Hashcat Generators
  include_tasks: hashcat_generators.yml
