---
# This playbook is responsible for installing and configuring ZeroTier VPN

- name: Install zerotier
  include_tasks: install.yml

- name: Join zerotier network
  include_tasks: join.yml

- name: Warn if not authorized
  include_tasks: auth_warn.yml