---
# Installs both the main PCFG toolset as well
# as the compiled PCFG repository

# Warning: The Compiled PCFG toolset only works with version
# 4.1 of the PCFG toolset rules, so you'll need to go back
# to an earlier release for the rules to work. I'm aware of this
# and fixing it is on my todo list.

# Clone the git repository for the PCFG toolset
- name: git checkout PCFG from github
  ansible.builtin.git:
    repo: https://github.com/lakiw/pcfg_cracker.git
    dest: "{{ git_repo_dir }}/pcfg_cracker"
    clone: yes
    update: yes

# Clone the git repository for the compiled PCFG toolset
- name: git checkout compiled PCFG from github
  ansible.builtin.git:
    repo: https://github.com/lakiw/compiled-pcfg.git
    dest: "{{ git_repo_dir }}/compiled_pcfg"
    clone: yes
    update: yes
  register: c_pcfg_update

# Only build the complied PCFG code if the repo has been updated or the system has been updated
- block:
  # Clean up compiled-pcfg install directory
  - name: Make Clean Compiled PCFG
    community.general.make:
      chdir: "{{ git_repo_dir }}/compiled_pcfg"
      target: clean

  # make compiled-pcfg
  - name: Make Compiled PCFG
    community.general.make:
      chdir: "{{ git_repo_dir }}/compiled_pcfg"

  # Create a symlink so that the compiled PCFG uses the same
  # ruleset as the standard PCFG toolset
  - name: Create a symbolic link for PCFG rules
    ansible.builtin.file:
      src: "{{ git_repo_dir }}/pcfg_cracker/Rules"
      dest: "{{ git_repo_dir }}/compiled_pcfg/Rules"
      state: link
  
  when: c_pcfg_update.changed or do_update_packages or do_upgrade_os